# Generated by Django 3.0.5 on 2020-04-20 15:20

import ShelterHeroesServer.storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=ShelterHeroesServer.storage.models.scramble_filename)),
            ],
        ),
    ]
