# Generated by Django 3.0.5 on 2020-05-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='race',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_animals', to='core.Shelter'),
        ),
    ]
